jobs:
  foundryvtt:
    srcdir: /source/files/foundryvtt
    destdir: /dest/foundryvtt
    retention: 30
    exclude:
      - __pycache__
      - .DS_Store
  appdata:
    srcdir: /source/appdata
    destdir: /dest/appdata
    retention: 30
    exclude:
      - __pycache__
      - .DS_Store
